config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'realisation' => 'pages#realisation'
  get 'expertise'  => 'pages#expertise'

  resources :pages do
    collection do
      post :contact_post
    end
  end
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?
  before_action :authenticate_user!, if: :devise_controller?, except: [ :authenticate_admin_user! ]

  def logged_in?
    !!current_user
  end

  def access_denied(exception)
    redirect_to user_root_path, :alert => exception.message
  end

  def user_root
    redirect_to url_of_target
  end

  protected
    def after_sign_in_path_for(resource)
      clear_sign_signin_flash
      url_of_target
    end

    def clear_sign_signin_flash
      flash.delete(:notice) if flash.keys.include?('notice')
    end

    def url_of_target
      if logged_in? && current_user.administrator?
        administration_dashboard_path
      elsif logged_in? && current_user.investor?
        dashboards_path
      elsif logged_in? && current_user.entrepreneur?
        entrepreneur_dashboards_path
      else
        root_path
      end
    end

    def authenticate_admin_user!
      if logged_in?
        unless current_user.administrator?
          flash[:error]= "Accès refusé | Vous n'avez pas les droits"
          redirect_to root_path
        end
      else
        redirect_to new_user_session_path, flash: { :error =>  t("devise.failure.unauthenticated") }
      end
    end
 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		#home
	end

	def about
		#about
	end

	def realisation
		#realisation
	end

	def expertise
		#expertise
	end


	def contact_post
    if params.values_at(:name, :phone, :email, :message).include? nil
      flash.now[:error] = 'Veuillez renseigner tous les champs du formulaire'
      render :contact
    else
      redirect_to contact_path(anchor: 'comfirmation')
      EvolutionDesignMailer.contact(params).deliver_now! rescue logger.warn('mail not sended')
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(name)
    case name
      when 'notice'
        'success'
      when 'error'
        'danger'
      when 'warning'
        'warning'
      when 'info'
        'info'
      else
        'danger'
    end
  end

  def clear_boolean value
    value ? "Oui" : "Non"
  end

  def download_media(id)
    root_path + "medias/download/#{id}"
  end

  def clear_status(status)
    "#{status.downcase}_status"
  end

  def display_media(id)
    root_path + "medias/display/#{id}"
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def new_investor
    Investor.new(role: 2)
  end

  def user_on_admin(user)
    case user.role
    when 'Administrator'
      administration_administrator_path(user)
    when 'Investor'
      administration_investor_path(user)
    when 'Entrepreneur'
      administration_entrepreneur_path(user)
    else
      root_path
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
	def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}"
  end

  def video_embed(url)
    youtube = false
    if url[/youtu\.be\/([^\?]*)/]
      id = $1
      youtube = true
    elsif url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      id = $5
      youtube = true
    elsif url[/dailymotion\.com\/video\/([a-zA-Z0-9]*)_/] || url[/dai\.ly\/([a-zA-Z0-9]*)/]
      id = $1
    end
    
    url = if youtube
      "https://www.youtube.com/embed/#{ id }"
    else
      "https://www.dailymotion.com/embed/video/#{ id }"
    end  
    
    %Q{<iframe title="video player" width="100%" height="400px" src="#{ url }" frameborder="0" allowfullscreen></iframe>}.html_safe
  end

  def active_link(action, controller)
    action.eql?(action_name) && controller_name.eql?(controller) ? 'active' : nil
  end

  def user_area_header_highlight(role)
    url = URI.parse(request.original_url)
    paths = url.path.split "/"
    'active' if logged_in? and current_user.role == role and paths.include? "mon-espace-personnel"
    'active' if logged_in? and current_user.role == role and paths.include? "mon-espace-personnel"
  end

  def display_image(media, width=nil, klass=nil)
    if media.present?
      image_tag url_for( root_path << "medias/display/#{media.id}"),  class: "img-responsive #{klass}", width: width
    end
  end 

  def display_resize_image(media, width, height=nil)
    if media.present?
      image_tag url_for( root_path << "medias/display/#{media.id}/#{width}/#{height}"),  class: 'img-responsive', width: "100%"
    end
  end

  def media_url(media)
    if media.present?
      root_path << "medias/display/#{media.id}"
    end
  end

  def link_to_linkedin(member)
    member.linkedin.present? ? "#{ member.linkedin },  target: '_blank'" : "#"
  end

  def objective_background(index)
    colors = {0 => "yellow", 1 =>"blue", 2 => "navy", 3 => "grey"}
    if index > 3
      index %=4 
    end
    colors[index]
  end

  def min_font_size(value)
    "font-size:0.91em;" if value < 12
  end

  def breadcrumb_link(name, title, path)
    if name == controller_name
      title
    else
      link_to title, path
    end
  end

  def is_active(action)       
    params[:action] != action ? "active" : nil        
  end

  def active_breadcrumb(name)
    name.eql?(controller_name) ? 'active' : nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
	def user_menu_highlight(action)
    action == params['action'] ? 'highlight' : ''
  end

  def selected_params params, attribute, model=nil
    if params
      params[attribute]
    elsif model.present?
      model.send attribute
    else
      ""
    end
  end

  def checked_params(params, attribute, value, db_value , model=nil)
    if params and params[attribute] == value
      true
    elsif model.present? and (model.send(attribute) == db_value)
      true
    else
      false
    end    
  end

  def user_profile_picture(user)
    if user.media.present?
      display_image user.media
    else
      if user.M?
        image_tag "investisseur.png", class: "img-responsive"
      else
        image_tag "entrepreneur.png", class: "img-responsive"
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<p>Copyright &copy; E.Design 2015</p>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<div class="brand">E.Design</div>
<div class="address-bar">BP 6740 Douala| Cameroun, E.Design | (+237) 74 83 59 37 - 93 94 15 46</div>

<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
            <a class="navbar-brand" href="index.html">E.Design</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="<%= active_link('home', 'pages') %>">
                    <%= link_to "Accueil", root_path  %>
                </li>

               <!--  <li class="<%= active_link('realisation', 'pages') %>">
                    <%= link_to "realisations", realisation_path  %>
                </li>
 -->
                 <li class="<%= active_link('about', 'pages') %>">
                    <%= link_to "A propos de nous", about_path  %>
                </li>
    
                <li class="<%= active_link('contact', 'pages') %>">
                    <%= link_to "Contact", contact_path  %>
                </li>

            </ul>

        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.present? %>
    <div class="alert alert-danger alert <%= flash_class(name.to_s)%> animated shake inscription_message" style="margin:60px 0 0 0 !important;">
      <!-- <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> -->
      <%= content_tag :div, :id => "flash_#{name}" do %>
        <% if msg.class.eql?(String) %>
          <%= msg.try :html_safe %>
        <% elsif msg.class.eql?(Array) %>
          <ul>
            <% msg.each do |m| %>
              <li><%= m.try :html_safe %></li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
   <title><%= (content_for? :title) ? (yield :title) : "EvolutionDesign" %></title>
  <meta charset="UTF-8">
  <!-- For mobile responsives -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Facebook Metadata-->
  <meta property="fb:page_id" content="" />
  <meta property="og:site_name" content = "EvolutionDesign" />
  <meta property="og:image" content="<%= asset_url('logo4.png') %>" />
  <meta property="og:title" content = "EvolotionDesign La plateforme du design industriel" />
  <meta property="og:description" content= "EvolotionDesign La plateforme du design industriel"/>

  <!-- Google+ Metadata /-->
  <meta itemprop="name" content="">
  <meta itemprop="image" content="<%= asset_url('logo4.png') %>" />

  <meta name="description" content="<%= (content_for? :meta_desc) ? (yield :meta_desc) : "EvolotionDesign La plateforme du design industriel" %> ">
  <% if content_for? :meta %>
    <%= yield :meta %>
  <% end %>

  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>
  <%= render 'layouts/header' %>
  <% unless content_for? :messages %>
      <%= render 'layouts/messages' %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
  <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">A propos du
                        <strong>Design Industriel</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-6">
                    <%= image_tag("slide-2.jpg", :alt => "slide-2.jpg", class: "img-responsive img-border-left") %>
                </div>
                <div class="col-md-6 text-justify">
                   <p>ED utilise son arts de savoir faire afin d'être toujours aussi proche de ses clients.</p> 
                   <p>Nous passons par une activité créative dont le but est d'élaborer les différentes caractéristiques d'objets, de procédés, de services et des systèmes dans lesquels ces derniers seront intégrés au cours de leur durée de vie. De nos jours le design est considéré comme le facteur central de l'humanisation novatrice des technologies et le premier facteur des échanges économiques et culturels.</p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">
                        <strong>Equipes</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-sm-4 text-center">
                    <%= image_tag("http://placehold.it/750x450", :alt => "http://placehold.it/750x450", class: "img-responsive") %>
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                     <%= image_tag("http://placehold.it/750x450", :alt => "http://placehold.it/750x450", class: "img-responsive") %>
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                     <%= image_tag("http://placehold.it/750x450", :alt => "http://placehold.it/750x450", class: "img-responsive") %>
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

    </div>
    <!-- /.container -->

app/views/pages/contact.html.erb
 <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Mes
                        <strong>Coordonnées</strong>
                    </h2>
                    <hr>
                </div>

                <div class="col-md-8">
                    <iframe width="100%" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15919.28138775457!2d9.7482151!3d4.057026!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x10610dbdc43636c7%3A0x2f7209fea45ab7a7!2sRoyal+Bilingual+College+Ndogbong!5e0!3m2!1sen!2sfr!4v1440499945088" width="100%" height="400" frameborder="0" style="border:0" allowfullscreen marginwidth="0"></iframe>
                </div>
                <div class="col-md-4">
                    <p>Téléphone:
                        <strong>(+237) 674 83 59 37 </strong>
                    </p>
                    <p>Email:
                        <strong><a href="mailto:name@example.com">brassack86@yahoo.fr</a></strong>
                    </p>
                    <p>Address:
                        <strong>BP 6740 Douala Cameroun</strong>
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Formulaire de
                        <strong>Contact</strong>
                    </h2>
                    <hr>
                    <br />
                    <div class="row">
                        <%= form_tag contact_post_pages_path, method: 'POST', id: 'contactMessage' do %>
                        <div class='form-group col-lg-4'>
                           <label>Name</label>
                          <input autofocus="autofocus" class="form-control" id="user_name" name="name" placeholder="Nom" required="required" type="text" />
                        </div>

                        <div class='form-group col-lg-4'>
                            <label>Email Address</label>
                          <input class="form-control" id="user_email" name="email" placeholder="Email" required="required" type="email" value="" />
                        </div>

                        <div class='form-group col-lg-4'>
                            <label>Téléphone</label>
                          <input class="form-control" id="user_phone" name="phone" placeholder="Téléphone" required="required" type="tel" />
                        </div>
    
                        <div class="form-group col-lg-12">
                         <label>Message</label>
                         <textarea class="form-control" name="message" rows="6"></textarea>
                        </div>
                        <div class="form-group col-lg-12">
                          <input name="commit" onclick="return validateCheckbox();" type="hidden" value="Envoyer"/>
                          <button type="submit" class="btn btn-default">Envoyé</button>
                        </div>
                    </div>
                  <% end %>
                </div>
            </div>
        </div>

    </div>

app/views/pages/expertise.html.erb
  <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">About
                        <strong>business casual</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-6">
                    <%= image_tag("slide-2.jpg", :alt => "slide-2.jpg", class: "img-responsive img-border-left") %>
                </div>
                <div class="col-md-6">
                    <p>This is a great place to introduce your company or project and describe what you do.</p>
                    <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets.</p>
                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Our
                        <strong>Team</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-sm-4 text-center">
                    <%= image_tag("http://placehold.it/750x450", :alt => "http://placehold.it/750x450", class: "img-responsive") %>
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                     <%= image_tag("http://placehold.it/750x450", :alt => "http://placehold.it/750x450", class: "img-responsive") %>
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                     <%= image_tag("http://placehold.it/750x450", :alt => "http://placehold.it/750x450", class: "img-responsive") %>
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

    </div>
    <!-- /.container -->

app/views/pages/home.html.erb
<!-- Container -->
<div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <%= image_tag("slide-1.jpg", :alt => "slide-1.jpg", class: "img-responsive img-full") %>
                            </div>
                            <div class="item">
                                <%= image_tag("slide-2.jpg", :alt => "slide-2.jpg", class: "img-responsive img-full") %>
                            </div>
                            <div class="item">
                                <%= image_tag("slide-3.jpg", :alt => "slide-3.jpg", class: "img-responsive img-full") %>
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <h2 class="brand-before">
                        <small>Bienvenue Chez</small>
                    </h2>
                    <h1 class="brand-name">Evolution Design</h1>
                    <hr class="tagline-divider">
                    <h2>
                        <small>
                            <strong>Concepeteur et Projecteur Industriel</strong>
                        </small>
                    </h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-justify">
                    <hr>
                    <h2 class="intro-text text-center">
                        <strong>Design Industriel</strong>
                    </h2>
                    <hr>
                    <%= image_tag("intro-pic.jpg", :alt => "intro-pic.jpg", class: "img-responsive img-border img-left") %>
                    <hr class="visible-xs">
                    <p>ED utilise son arts de savoir faire afin d'être toujours aussi proche de ses clients.</p>
                    <p>Nous passons par une activité créative dont le but est d'élaborer les différentes caractéristiques d'objets, de procédés, de services et des systèmes dans lesquels ces derniers seront intégrés au cours de leur durée de vie. De nos jours le design est considéré comme le facteur central de l'humanisation novatrice des technologies et le premier facteur des échanges économiques et culturels.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box text-justify">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">
                        <strong>Design Architectural</strong>
                    </h2>
                    <hr>
                    <p>Pour tout ce qui est conception des plans; réalisations des maquettes; montage des dossiers de permis de Bâtir; dimensionnement des structures en bois, aciers et bétons armé; tuyauterie industrielle; chaudronnerie; conception d'objets et systèmes personnalisé, Infographie, impression numérique. 
                        <a href="<%= contact_path %>">Contactez-nous</a>
                    </p>

                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

app/views/pages/realisation.html.erb
  <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">About
                        <strong>business casual</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-6">
                    <%= image_tag("slide-2.jpg", :alt => "slide-2.jpg", class: "img-responsive img-border-left") %>
                </div>
                <div class="col-md-6">
                    <p>This is a great place to introduce your company or project and describe what you do.</p>
                    <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets.</p>
                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Our
                        <strong>Team</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-sm-4 text-center">
                    <%= image_tag("http://placehold.it/750x450", :alt => "http://placehold.it/750x450", class: "img-responsive") %>
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                     <%= image_tag("http://placehold.it/750x450", :alt => "http://placehold.it/750x450", class: "img-responsive") %>
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                     <%= image_tag("http://placehold.it/750x450", :alt => "http://placehold.it/750x450", class: "img-responsive") %>
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

    </div>
    <!-- /.container -->

app/views/shared/_error_messages.html.erb
 
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "erreur") %> 
        ont empêché <%= object.class.to_s.underscore.humanize.downcase %>
        d'enregistrer votre inscription</h2>
    <p>Merci de corriger ces champs :</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <table class="microposts" summary="User microposts">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class="micropost">
    <span class="user">
      <%= link_to feed_item.user.nom, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posté il y a <%= time_ago_in_words(feed_item.created_at) %>.
    </span>
  </td>
  <% if current_user?(feed_item.user) %>
  <td>
    <%= link_to "supprimer", feed_item, :method => :delete,
                                     :confirm => "Etes-vous certain ?",
                                     :title => feed_item.content %>
  </td>
  <% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Soumettre" %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
          <%= pluralize(@user.following.count, "Auteurs suivis") %>
          </span>
        </a>
      </td>
      <td>
        <a href="
<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "Lecteur") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.nom %>
    </span>
    <span class="microposts">
      <%= pluralize(current_user.microposts.count, "micropost") %>
    </span>
  </a>
</div>